[logger]
level = "INFO"

[storage]
type = "sql"
dsn="host=localhost port=5432 user=calendar password=password dbname=calendar sslmode=disable"

[scheduler]
periodSeconds=10

[queue]
dsn="amqp://guest:guest@localhost:5672/"
name="notifications"
