[logger]
level = "INFO"

[storage]
type = "sql"
dsn="host=calendar_db port=5432 user=calendar password=password dbname=calendar sslmode=disable"

[scheduler]
periodSeconds=10

[rabbit]
dsn="amqp://guest:guest@rabbitmq:5672/"
queue="notifications"
