[logger]
level = "INFO"

[storage]
type = "sql"
dsn="host=calendar_db port=5432 user=calendar password=password dbname=calendar sslmode=disable"

[http]
host = "0.0.0.0"
port = "8888"

[grpc]
host = "0.0.0.0"
port = "5000"
