version: "3"

services:
  app:
    build:
      dockerfile: build/Dockerfile
      context: .
      args:
        - CONFIG_FILE=./configs/config.sql.toml
    ports:
      - 3000:3000
    depends_on:
      calendar_db:
        condition: service_healthy
  calendar_db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calendar -d calendar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.11.15-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - './rmqdata:/var/lib/rabbitmq/mnesia/'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
